language: python
python:
  - '2.7'
  - '3.6'
install:
  - pip install -U pip setuptools
  - pip install -Ur requirements-test.txt --upgrade-strategy eager
script: py.test tests/ -v --cov wrapanapi
after_success:
  - coveralls
deploy:
  provider: pypi
  user: mshriver
  password:
    secure: VXidnpm6NcQk0ZKMUiM85RkbLhmmJeRmj36jksgXUjKH210Lfs1sYZ7c8YJduWHVLCu2yZWDUbBfRVJKBYZ4lPzjby34N1HOaA4TsJFza/zerVqKt2mv0WB7SyLXLWVmcJOORmjGB0NFL6zJHt6St5nb9Gtf4y30lf3wK+1aSXBLS8nI6CWzbSOUFrBssiezEEblfCShXFwgG7FpDFZWIRy8GSMGuCkxwexhjMN76Ktzr+/O2fq+qoghUKiXel+tjffOJ+z44yw25yRDVPEsVTfB2feSDCcam55AGhmCO3b0M34yi4rrkMqdW8PopRW2S1TMZiZdLLPaQn28VILSOvsb3N1zEPhIucsguldAHy1SkQQqwXJJ1Biok7+WuKk2bN1U3FfT1SIH/vmM3zdLDA2RIEnH9ig9TRrZklcminnM3fr3fPA8wC+b60W/MN9uVVmtPf5qJlC3+0sfOMIhZdBDnDLoyyBIBk3W5b546jckBlep3FkN10rTpSGpNOdYgVxsby4+wq4+Q9I4BiQXAc/+ayHhOkA98295JCUFZR+IA7ZUU3o/07p5kzOMStJi09tz7bTnTPmIpHMXZU3B8wqGAipqFIiQXRS7n8IbPACRPpJ12KplHaY/OlKcISJRwgj7biLTsVN3PE7D1DQSn3vjvcNnBVErSqxRFEiE2HE=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ManageIQ/wrapanapi

